[workspace]
resolver = "3"
members = ["crates/glyph-core", "crates/dataset-gen", "crates/glyph-infer", "crates/glyph-nn"]

[workspace.package]
edition = "2024"
version = "0.0.1"
authors = ["potistudio <potistudio@proton.me>"]
license = "MIT"
publish = false

[profile.release]
codegen-units = 1
lto = true

[workspace.dependencies]
glyph-core = { path = "crates/glyph-core" }
glyph-nn = { path = "crates/glyph-nn" }
